### ISSUE TITLE
Try to use ingress to do outside loadbanlancing.

### ISSUE THREAD

**Issue by shiywang** [nursingengineeringlab/hcm-k8s#1]
For expose and load balancing our services, we can use 
1. load banlancer type service
2. Nodeport type service
3.  External name type service e.g. below

```
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  type: ExternalName
  externalName: my.database.example.com
```

But for each every service has an independent load balancing is not good, we can use ingress to "central" manage all our service and do load balancing.  

For example we have a website called: `https://cafe.example.com`, including `https://cafe.example.com/coffee` is coffee ordering system. 
`https://cafe.example.com/tea` is tea ordering system. 
we have two k8s deployment for both service so we can use ingress to have different url to load balance different service/deployment. like below:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
spec:
  tls:
  - hosts:
    - cafe.example.com
    secretName: cafe-secret
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```
